# Generated by Django 2.2.5 on 2019-10-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpToken',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='トークンID')),
                ('token', models.CharField(max_length=32, verbose_name='トークン')),
            ],
        ),
    ]
