# Generated by Django 2.2.5 on 2019-10-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_token', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuptoken',
            name='available',
            field=models.BooleanField(default=False, verbose_name='アクティベート状況'),
        ),
        migrations.AddField(
            model_name='signuptoken',
            name='target',
            field=models.CharField(default='hogehoge', max_length=64, verbose_name='対象ユーザ'),
        ),
    ]
