# Generated by Django 2.2.5 on 2019-09-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190923_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='equip_attribute',
            field=models.CharField(choices=[('book', '書籍'), ('depc', 'デスクトップPC'), ('lapc', 'ノートPC'), ('wkst', 'ワークステーション'), ('dspl', 'PCディスプレイ'), ('pcsp', 'PC周辺機器'), ('vrdv', 'VRデバイス'), ('ardv', 'ARデバイス'), ('prjc', 'プロジェクター'), ('scrn', 'スクリーン'), ('smph', 'スマートフォン'), ('tbdv', 'タブレット端末'), ('tool', '工具類')], max_length=4, null=True, verbose_name='種類'),
        ),
    ]
