# Generated by Django 2.2.5 on 2019-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190929_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, verbose_name='備考'),
        ),
    ]
