# Generated by Django 2.2.5 on 2019-09-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='registered_date',
            field=models.DateTimeField(auto_now=True, verbose_name='登録年月日'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='equip_attribute',
            field=models.CharField(choices=[('book', '書籍'), ('depc', 'デスクトップPC'), ('lapc', 'ノートPC'), ('wkst', 'ワークステーション'), ('dspl', 'PCディスプレイ'), ('pcsp', 'PC周辺機器'), ('vrdv', 'VRデバイス'), ('ardv', 'ARデバイス'), ('prjc', 'プロジェクター'), ('scrn', 'スクリーン'), ('smph', 'スマートフォン'), ('tbdv', 'タブレット端末')], max_length=2, verbose_name='種類'),
        ),
    ]
