# Generated by Django 2.2.5 on 2019-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190913_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='equip_status',
            field=models.CharField(choices=[('avlb', '利用可能'), ('lend', '貸出中'), ('asgn', '割当中'), ('lost', '紛失')], max_length=4, null=True, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='equip_attribute',
            field=models.CharField(choices=[('book', '書籍'), ('depc', 'デスクトップPC'), ('lapc', 'ノートPC'), ('wkst', 'ワークステーション'), ('dspl', 'PCディスプレイ'), ('pcsp', 'PC周辺機器'), ('vrdv', 'VRデバイス'), ('ardv', 'ARデバイス'), ('prjc', 'プロジェクター'), ('scrn', 'スクリーン'), ('smph', 'スマートフォン'), ('tbdv', 'タブレット端末')], max_length=4, null=True, verbose_name='種類'),
        ),
    ]
